<?php

use Baidu\Aip\AipNlp;

/**
 * Baidu AI.
 */
function baidu_ai() {
  $app_id = variable_get('baidu_ai_app_id');
  $api_key = variable_get('baidu_ai_api_key');
  $secret_key = variable_get('baidu_ai_secret_key');
  $ai_client = new AipNlp($app_id, $api_key, $secret_key);
  return $ai_client;
}

/**
 * Implements hook_config_form().
 */
function baidu_aip_config_form() {
  $homepage_seo = variable_get('homepage_seo');
  $searchpage_seo = variable_get('searchpage_seo');
  $form['baidu_ai_app_id'] = array(
    '#type' => 'textfield',
    '#title' => 'App ID',
    '#default_value' => variable_get('baidu_ai_app_id')
  );
  $form['baidu_ai_api_key'] = array(
    '#type' => 'textfield',
    '#title' => 'Api Key',
    '#default_value' => variable_get('baidu_ai_api_key')
  );
  $form['baidu_ai_secret_key'] = array(
    '#type' => 'textfield',
    '#title' => 'Secret Key',
    '#default_value' => variable_get('baidu_ai_secret_key')
  );
  $form['form_id'] = 'baidu_ai_setting_form';
  $form['name'] = '百度AI设置';

  return $form;
}
